# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - iotlabfuncmkhamuliak

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🔐 Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_054F630222CF4B68B99DC4BE73F4A025 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_857AC49C2A0541D8BDE41577C88C79D4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_22BF0D4B74F341A7BB4C99139D76E575 }}

      - name: 🚀 Deploy to Azure Functions (Remote Build)
        uses: Azure/functions-action@v1
        with:
          app-name: 'iotlabfuncmkhamuliak'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
